# Generated by Django 4.1.7 on 2023-05-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identrega', models.CharField(max_length=200)),
                ('item', models.TextField()),
                ('direction', models.TextField()),
                ('transportist', models.CharField(max_length=200)),
            ],
        ),
    ]
